### ISSUE TITLE
添加了 Since 底部依旧没显示？

### ISSUE THREAD

**Issue by iLeyar** [ahonn/hexo-theme-even#3]
![image](https://cloud.githubusercontent.com/assets/4384122/14208022/eac2a0d2-f84f-11e5-9c75-f96eb1814327.png)

设置如下：
![image](https://cloud.githubusercontent.com/assets/4384122/14208048/05a6743c-f850-11e5-813c-1abc1cd62192.png)

**Comment by ahonn** [comment]
这个是blog的配置里哦，不是主题的。看来真的要好好写文档了




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周五 4月1日 21:24
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
主题：[ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)

**Comment by ahonn** [comment]
@iLeyar 感觉还需要好好整理一下这些配置项，之后会把所有主题配置项放 theme/even/_config.yml 里。因为我用太久了，所有得新建个 hexo 项目目录来看看哪些是原来 init 就有的，尽量保持原 blog 的 config 不需要添加。这个其实之前也有点困扰，写到 blog 的 config 的话，多个主题之间的配置可能会乱。这一点我还没搞好。

**Comment by iLeyar** [comment]
@ahonn  已经好了～ btw，期待你的新主题。
对于这个你遇到的难题我也无能为力...

**Comment by ahonn** [comment]
@iLeyar  文档我重新写了，应该没有什么遗漏

**Comment by iLeyar** [comment]
@ahonn  归档文章数我是在根目录配置文件里添加的，似乎也能生效。

**Comment by ahonn** [comment]
因为这个是插件实现的，所以都可以。不过建议放主题里面，毕竟不同主题的数量可能不一样～不过要是就一个主题那就没什么关系啦




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周六 4月2日 00:39
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)

**Comment by iLeyar** [comment]
@ahonn 总觉得主题字体有点小。你觉得这个人的字体怎么样？我听喜欢他的排版的。http://ipotato.me/article/33

**Comment by ahonn** [comment]
是说手机上看小？好像的确可以加大一点点。好像标题的话手机上的确小了。明天改改改。那么晚还不睡




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周六 4月2日 01:22
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)

**Comment by ahonn** [comment]
我一直有在考虑导航栏要不要加点装饰，你觉得要不要加呢




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周六 4月2日 01:22
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)

**Comment by iLeyar** [comment]
@ahonn 加啥？

**Comment by ahonn** [comment]
对角框啊什么的，但又觉得好像不好看。早上把字体稍微改大了一点点，不知道你觉得如何，没有昨天你发的那个博客里面大，具体可以看看我博客上的效果。总感觉字太大不精致。然后我博客上有个侧边栏的，不过感觉不是很好看，给给意见～




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周六 4月2日 10:11
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)

**Comment by iLeyar** [comment]
![image](https://cloud.githubusercontent.com/assets/4384122/14223979/0fe8f6ee-f8bf-11e5-8264-43342a2bc12c.png)
给你看下我这的效果图。

**Comment by iLeyar** [comment]
似乎 Logo 可以往左调一点。

**Comment by ahonn** [comment]
字体果然还是要统一一下，晚上回去我把字体方到文件夹里面吧。另外LOGO你是说左对齐还是说移一点点？




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周六 4月2日 10:40
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] 添加了 Since 底部依旧没显示？ (#3)
